sudo: required
dist: bionic
language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install ansible
  - pip install flake8
  - pip install wheel       # for ansible-test
  - pip install Jinja2      # for ansible-test
  - pip3 install pyyaml     # for ansible-test
  - pip3 install voluptuous # for ansible-test
  - pip install pyyaml      # for compile test with Python2
  - pip3 install pylint     # for ansible-test
  - pip install yamllint    # for ansible-test
  - pip install pytest      # for pytest
  - pip install pytest-mock # for pytest
  - pip3 install rstcheck
  - pip3 install ansible-doc-extractor
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install lxml
  - pip3 install lxml
  - ansible --version
  
env:
  global:
    secure:  Rg6rERczObW20sL4pZRqZBHUAQb4whSakQBSLMVh1fnxvQ9s5UVr3lDOoIPQ22TAeqQmr1kz1N21ithwt2lCwT3Slm0IfAdACfVcn3VmgvSwXgJVNQVjqjXVn/qhf+AV8+bQu4J/O3g1o7ZaKSWsY01aTx0HWwl3GCb8PBo2MhEiQfN+v/PQP5xaLLH5UcM35iBTwuk+NW9tUrtZcC3zgbm2VBwpm8AFJkF6wmQc2jZURMBRBxa6SV7epI1RI3oKsMx/9dnsD8FaZnhB2GRdmQrdphBZwpQxPegWwEk8g7FQz2OGkHuW2XgmVXDPNM5Sz9foX6fWfICBnHvMKiqaHC1KdQDcNTkB2m1d0/3RZNWPyE78PZ0gk7lMXaK918SQLZW7muKAP+wq1ID2Rsy3STI0WZd/LJJZcuNwUb3A6hDt5AzmyfBXPiyin9/mQSckCY4EXmFiUlFxUZAH8lj9zE65xMF6ZMRFeEDMmGkUkFyb0YR2IXH/hiQ8TV+ru4xmUF3JZm9BTmE5OCsLtJH5Q48EOXrTrGwqCFe0MA1JnsFAVvnGnPVUxikaOI44P3vDyLMt03+T0sQ1YTS7Js0VbnfcM3kOV4Kq0KY02vo7ZAz4YNcsBh2PL4hs5RjjCKSFVsjfB+I+k519CGKVNETf28vhOjn2I8LTHYLrZxavRGg=

# command to run tests
script:

  # With flake ignore
  #  E402: <module> level import not at top of file (as per Ansible module developement)
  #  W503: line break before binary operator (PEP8 advices to put logical operator ahead)
  - flake8 plugins/modules/* --max-line-length=160 --ignore=E402,W503
  - flake8 plugins/module_utils/* --max-line-length=160 --ignore=E402,W503
  - flake8 tests/unit/*/* --max-line-length=160 --ignore=E402,W503
  - ansible-galaxy collection build
  - ansible-galaxy collection install ibm-power_hmc*
  - build_path=`pwd`
  - cd /home/travis/.ansible/collections/ansible_collections/ibm/power_hmc

  - pyenv global 3.7 2.7 
  - ansible-test sanity --python 2.7 --skip-test shellcheck
  - ansible-test sanity --python 3.7 --skip-test shellcheck
  - cd /home/travis/.ansible/collections/
  - python -m pytest
  - cd $build_path
  - bash devops/bin/gen_doc.sh

# push the generated documentation using GitHub Pages
deploy:
    provider: pages
    strategy: git
    skip_cleanup: true
    token: $GITHUB_API_KEY
    local_dir: docs/build
    keep_history: true
    on:
        branch: alpha-v1.1.0
